image: mcr.microsoft.com/playwright:v1.57.0-jammy
 
stages:
  - test
  - report
  - pages
 
variables:
  CI: "true"
  ALLURE_RESULTS_DIR: allure-results
  ALLURE_REPORT_DIR: allure-report
 
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
 
playwright_tests:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test

  artifacts:
    when: always
    paths:
      - playwright-report/
      - allure-results/
    expire_in: 7 days

  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "failed" ]; then
        curl -X POST -H 'Content-type: application/json' \
        --data "{
          \"channel\": \"$SLACK_CHANNEL\",
          \"text\": \" *Playwright tests FAILED*\\nProject: *$CI_PROJECT_NAME*\\nBranch: *$CI_COMMIT_REF_NAME*\\nPipeline: <$CI_PIPELINE_URL|Open pipeline>\"
        }" $SLACK_WEBHOOK_URL

 


allure_report:
  stage: report
  image: frankescobar/allure-docker-service

  dependencies:
    - playwright_tests
  script:
    - allure generate allure-results --clean -o allure-report

  artifacts:
    when: always
    paths:
      - allure-report/
    expire_in: 14 days
 


pages:
  stage: pages
  dependencies:
    - allure_report

  script:

    - mkdir -p public
    - cp -r allure-report/* public/

  artifacts:

    paths:

      - public

  only:

    - master

    - main

  after_script:

    - |

      curl -X POST -H 'Content-type: application/json' \

      --data "{

        \"channel\": \"$SLACK_CHANNEL\",

        \"text\": \" *Allure report is ready!*\\nProject: *$CI_PROJECT_NAME*\\nBranch: *$CI_COMMIT_REF_NAME*\\n Report: https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME/\"

      }" $SLACK_WEBHOOK_URL

 